# .github/workflows/preview.yml
name: Deploy PR previews

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup kramdown-rfc
        run: gem install kramdown-rfc
      
      - name: Setup xml2rfc
        run: |
          sudo apt-get update
          sudo apt-get install -y xml2rfc

      - name: Make files
        run: |
          xml2rfc --html openid-risc-profile-specification-1_0.xml

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
